config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'devise/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'events#index'

  resources :events do
    resources :comments, only: [:create, :destroy]
    resources :subscriptions, only: [:create, :destroy]
    resources :photos, only: [:create, :destroy]
    post :show, on: :member
  end

  resources :users, only: [:show, :edit, :update]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :event
  belongs_to :user, optional: true

  validates :body, presence: true
  validates :user_name, presence: true, unless: -> { user.present? }

  def user_name
    return  user.name if user.present?
    super
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_event, only: [:create, :destroy]
  before_action :set_comment, only: :destroy

  def create
    @new_comment = @event.comments.build(comment_params)
    @new_comment.user = current_user

    if attempt_to_access_to_private_event?(@event)
      flash[:alert] = I18n.t('pundit.not_authorized')
      return redirect_to @event
    end

    if @new_comment.save
      notify_subscribers(@event, @new_comment)
      flash[:notice] = I18n.t('controllers.comments.created')
      redirect_to @event
    else
      flash.now[:alert] = I18n.t('controllers.comments.error')
      render 'events/show'
    end
  end

  def destroy
    type, message = :notice, I18n.t('controllers.comments.destroyed')

    if current_user_can_edit?(@comment)
      @comment.destroy!
    else
      type, message = :alert, I18n.t('controllers.comments.error')
    end

    flash[type] = message
    redirect_to @event
  end

  private

  def set_event
    @event = Event.find(params[:event_id])
  end

  def set_comment
    @comment = @event.comments.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body, :user_name)
  end

  def notify_subscribers(event, comment)
    all_emails = (event.subscriptions.map(&:user_email) + [event.user.email]).uniq
    all_emails -= [current_user.email] if current_user
    all_emails.each { |mail| EventMailer.comment(event, comment, mail).deliver_later }
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.haml
.buffer-bottom
  %p= comment.body
  %p
    %span
      - if comment.user.present?
        = render partial: 'users/user', object: comment.user
      - else
        %em
          %strong= comment.user_name
    %em= l comment.created_at, format: :long
    - if current_user_can_edit?(comment)
      = link_to(fa_icon('trash'), event_comment_path(comment.event, comment), |
          method: :delete, data: {confirm: t('are_you_sure')})                |

app/views/comments/_form.html.haml
= form_for [@event, comment] do |f|
  = render partial: 'partials/form_errors', locals: { model: comment }
  .form-group
    = f.label :body
    = f.text_area :body, class: 'form-control'
  - unless user_signed_in?
    .form-group
      = f.label :user_name
      = f.text_field :user_name, class: 'form-control'
  .actions
    = f.submit 'Отправить', class: 'btn btn-primary'