config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'devise/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'events#index'

  resources :events do
    resources :comments, only: [:create, :destroy]
    resources :subscriptions, only: [:create, :destroy]
    resources :photos, only: [:create, :destroy]
    post :show, on: :member
  end

  resources :users, only: [:show, :edit, :update]
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :subscribers, through: :subscriptions, source: :user
  has_many :photos, dependent: :destroy

  validates :title, presence: true, length: { maximum: 255 }
  validates :address, presence: true
  validates :datetime, presence: true

  def visitors
    subscribers + [user]
  end

  def pincode_valid?(pin2chek)
    pincode == pin2chek
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_event, only: [:show, :destroy, :edit, :update]
  after_action :verify_authorized, only: [:show, :destroy, :edit, :update]
  after_action :verify_policy_scoped, only: :index

  def index
    @events = policy_scope(Event)
  end

  def show
    if params[:pincode].present? && @event.pincode_valid?(params[:pincode])
      cookies.permanent["events_#{@event.id}_pincode"] = params[:pincode]
    end

    authorize @event

    @new_comment = @event.comments.build(params[:comment])
    @new_subscription = @event.subscriptions.build(params[:subscription])
    @new_photo = @event.photos.build(params[:photo])
  end

  def new
    @event = current_user.events.build
  end

  def edit
    authorize @event
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      flash[:notice] = I18n.t('controllers.events.created')
      redirect_to @event
    else
      render :new
    end
  end

  def update
    authorize @event

    if @event.update(event_params)
      flash[:notice] = I18n.t('controllers.events.updated')
      redirect_to @event
    else
      render :edit
    end
  end

  def destroy
    authorize @event

    @event.destroy
    flash[:notice] = I18n.t('controllers.events.destroyed')
    redirect_to events_url
  end

  protected

  def user_not_authorized
    unless policy(@event).show?
      flash.now[:alert] = I18n.t('controllers.events.wrong_pincode') if params[:pincode].present?
      render :password_form
    else
      super
    end
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :address, :datetime, :description, :pincode)
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def event_photo(event)
    photos = event.photos.persisted

    return photos.sample.photo.url if photos.any?
    asset_url('event.jpg')
  end

  def event_thumb(event)
    photos = event.photos.persisted

    return photos.sample.photo.thumb.url if photos.any?
    asset_url('event_thumb.jpg')
  end
end

app/views/events/_event.html.haml
.col-sm-6.col-md-5
  .thumbnail
    = content_tag 'div', '', class: 'event-background',                |
      style: "background-image: url(#{asset_path('event_thumb.jpg')})" |
    .thumbnail-inner.event-info-inner
      .caption
        .event-description
          %h3
            = link_to event.title, event_path(event)
          %h3
            %small
              = l event.datetime, format: :long
          .buffer-both
            = event.address
        %div
          - event.visitors.each do |user|
            = image_tag user_avatar_thumb(user), class: 'img-icon', title: user.name

app/views/events/_form.html.haml
= form_for(@event) do |f|
  = render partial: 'partials/form_errors', locals: {model: @event}
  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control'
  .form-group
    = f.label :address
    = f.text_field :address, class: 'form-control'
  .form-group
    = f.label :datetime
    %p= f.datetime_select :datetime, class: 'form-control'
  .form-group
    = f.label :description
    = f.text_area :description, class: 'form-control'
  .form-group
    = f.label :pincode
    = f.text_field :pincode, class: 'form-control'
  .actions
    = f.submit 'Сохранить', class: 'btn btn-primary'
    или #{link_to 'вернуться', :back}

app/views/events/edit.html.haml
%h2 Редактирование события
.row
  .col-md-6.buffer-top
    = render 'form'

app/views/events/index.html.haml
%h1 События
.buffer-both
  = link_to 'Создать событие', new_event_path, class: 'btn btn-success'
.row.buffer-bottom
  = render partial: 'events/event', collection: @events

app/views/events/new.html.haml
%h2 Новое событие
.row
  .col-md-6.buffer-top
    = render 'form'

app/views/events/password_form.html.haml
%h2 Введите код доступа
= form_tag('', method: 'post') do |f|
  .form-group
    = label :pincode, 'Код доступа'
    = text_field_tag :pincode, params[:pincode], class: 'form-control'
  .actions
    = submit_tag 'ОК', class: 'btn btn-primary'
.buffer-top
  = link_to 'На главную', events_path

app/views/events/show.html.haml
.event
  .event-info.row
    .col-md-12
      = content_tag 'div', '', class: 'event-background',      |
        style: "background-image: url(#{event_photo(@event)})" |
      .event-info-inner.row
        .col-md-6
          .event-description
            %h2= @event.title
            %h3= l @event.datetime, format: :long
            %h3
              %small= link_to @event.address,                      |
                  "https://yandex.ru/maps/?text=#{@event.address}" |
            %p= @event.description
            - if current_user_can_edit?(@event)
              .buffer-both
                = link_to 'Изменить', edit_event_path(@event), class: 'btn btn-primary'
                = link_to 'Удалить', event_path(@event), method: :delete,       |
                  data: { confirm: t('are_you_sure') }, class: 'btn btn-danger' |
        .col-md-6
          #map.event-map(data-address="#{@event.address}")
  .row
    .col-md-8
      .event-photos
        .event-photos-gallery
          .owl-carousel{data: {count: @event.photos.except(@new_photo).count}}
            = render partial: 'photos/photo', collection: @event.photos.except(@new_photo)
        - if current_user
          .event-photo-form.buffer-top
            = render partial: 'photos/form', locals: { photo: @new_photo || @event.photos.build }
      .event-comments.buffer-top
        = render partial: 'comments/form', locals: { comment: @new_comment || @event.comments.build }
        .buffer-both
          = render partial: 'comments/comment', collection: @event.comments.except(@new_comment).order(created_at: :desc)
    .col-md-4
      .event-owner
        %h4 Зовёт:
        %p= render partial: 'users/user', object: @event.user
      .event-subscriptions
        %h4 Пойдут:
        %div
          %p
            - subsсribers = @event.subscriptions.except(@new_subscription)
            - if subsсribers.any?
              = render partial: 'subscriptions/subscription', collection: subsсribers
            -else
              Пока никто не записался
      - unless current_user == @event.user
        .event-subscription-form
          %h4 Я пойду:
          %div
          - unless current_user
            = render partial: 'subscriptions/form', locals: { subscription: @new_subscription || @event.subscriptions.build }
          - else
            - if current_user.subscriptions.pluck(:event_id).include?(@event.id)
              - subscription = current_user.subscriptions.find_by(event_id: @event.id)
              = link_to 'Отписаться', event_subscription_path(subscription.event, subscription), |
                  method: :delete, data: { confirm: t('are_you_sure') }, class: 'btn btn-danger' |
            - else
              = render partial: 'subscriptions/form', locals: { subscription: @new_subscription || @event.subscriptions.build }