config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'devise/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'events#index'

  resources :events do
    resources :comments, only: [:create, :destroy]
    resources :subscriptions, only: [:create, :destroy]
    resources :photos, only: [:create, :destroy]
    post :show, on: :member
  end

  resources :users, only: [:show, :edit, :update]
end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :photo, PhotoUploader

  belongs_to :event
  belongs_to :user

  validates :photo, presence: true

  scope :persisted, -> { where "id IS NOT NULL" }
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_event, only: [:create, :destroy]
  before_action :set_photo, only: :destroy

  def create
    @new_photo = @event.photos.build(photo_params)
    @new_photo.user = current_user

    if attempt_to_access_to_private_event?(@event)
      flash[:alert] = I18n.t('pundit.not_authorized')
      return redirect_to @event
    end

    if @new_photo.save
      notify_subscribers(@event, @new_photo)
      flash[:notice] = I18n.t('controllers.photos.created')
      redirect_to @event
    else
      flash.now[:alert] = I18n.t('controllers.photos.error')
      render 'events/show'
    end
  end

  def destroy
    type, message = :notice, I18n.t('controllers.photos.destroyed')

    if current_user_can_edit?(@photo)
      @photo.destroy
    else
      type, message = :alert, I18n.t('controllers.photos.error')
    end

    flash[type] = message
    redirect_to @event
  end

  private

  def set_event
    @event = Event.find(params[:event_id])
  end

  def set_photo
    @photo = @event.photos.find(params[:id])
  end

  def photo_params
    params.fetch(:photo, {}).permit(:photo)
  end

  def notify_subscribers(event, photo)
    all_emails = (event.subscriptions.map(&:user_email) + [event.user.email] - [photo.user.email]).uniq
    all_emails.each { |mail| EventMailer.photo(event, photo, mail).deliver_later }
  end
end

app/views/photos/_form.html.haml
= form_for [@event, photo], html: { multipart: true } do |f|
  = render partial: 'partials/form_errors', locals: { model: photo }
  .form-group
    = f.label :photo
    = f.file_field :photo
  .actions
    = f.submit 'Загрузить', class: 'btn btn-primary'

app/views/photos/_photo.html.haml
- description = "Добавил #{render partial: 'users/user', object: photo.user}"
- trash = link_to(fa_icon('trash'), event_photo_path(photo.event, photo), |
            method: :delete, data: { confirm: t('are_you_sure') })        |
- description += trash if current_user_can_edit?(photo)
= link_to image_tag(photo.photo.thumb.url), photo.photo.url, data: {          |
    toggle: 'lightbox', gallery: "event#{photo.event.id}", title: description |
  }                                                                           |